version: "2"
exclude_patterns:
- "**/*.spec.ts"
- "**/*.spec.js"
- "**/*.d.ts"

checks:
  method-complexity:
    config:
      threshold: 10
  return-statements:
    config:
      threshold: 5
  similar-code:
    config:
      threshold: 10
  identical-code:
    config:
      threshold: 10
