env:
  browser: true
  es2021: true
  node: true
extends: standard-with-typescript
plugins:
  - jsdoc
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  comma-dangle: “always-multiline”
