env:
  browser: true
  es2021: true
  node: true
extends: 
  - standard
  - plugin:sonarjs/recommended-legacy
  - plugin:jsdoc/recommended-typescript-flavor
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  jsdoc/valid-types: 0
  comma-dangle: [error, always-multiline]
  key-spacing: ["error", { "mode": "minimum" }]
  no-multi-spaces: [error, { exceptions: { Property: true, ObjectExpression: true }}]
  sonarjs/cognitive-complexity: ["error", 10]
  max-lines-per-function: ["warn", 75]
settings:
  jsdoc:
    mode: typescript
    permissive: true
